
    export const products = [
      {
        id: 1,
        name: "Air Max",
        price: "$120",
        description: "The latest in comfort and style.",
        image: "shoe1.jpg",
        link: "/product/1",
      },
      {
        id: 2,
        name: "Classic Sneakers",
        price: "$80",
        description: "Timeless design with modern flair.",
        image: "shoe2.jpg",
        link: "/product/2",
      },
      {
        id: 3,
        name: "Running Shoes",
        price: "$100",
        description: "Built for speed and durability.",
        image: "shoe3.jpg",
        link: "/product/3",
      },
      {
        id: 4,
        name: "Casual Trainers",
        price: "$110",
        description: "Perfect for your daily adventures.",
        image: "shoe4.jpg",
        link: "/product/4",
      },
      {
        id: 5,
        name: "Sports Runners",
        price: "$130",
        description: "High-performance shoes for athletes.",
        image: "shoe5.jpg",
        link: "/product/5",
      },
      {
        id: 6,
        name: "Vintage Sneakers",
        price: "$90",
        description: "Retro vibes with modern comfort.",
        image: "shoe6.jpg",
        link: "/product/6",
      },
      {
        id: 7,
        name: "Luxury Loafers",
        price: "$150",
        description: "Sophistication meets comfort.",
        image: "shoe7.jpg",
        link: "/product/7",
      },
      {
        id: 8,
        name: "Trail Runners",
        price: "$140",
        description: "Durable and rugged for any terrain.",
        image: "shoe8.jpg",
        link: "/product/8",
      },
      {
        id: 9,
        name: "Comfy Boots",
        price: "$180",
        description: "Durable and rugged for any terrain.",
        image: "shoe9.jpg",
        link: "/product/9",
      },
    ];